// generators/headers.ts - SQL dump header generation

import type { DatabaseFormat } from '../types.js';

/**
 * Generate header comments for SQL dump
 */
export function generateHeader(format: DatabaseFormat): string {
  const timestamp = new Date().toISOString();
  return `-- SQL Dump generated by sqlew
-- Date: ${timestamp}
-- Target: ${format.toUpperCase()}
--
-- This dump is wrapped in a transaction.
-- On error, all changes will be rolled back automatically.
--
-- Usage (empty database):
--   ${format === 'mysql' ? 'mysql mydb < dump.sql' : format === 'postgresql' ? 'psql -d mydb -f dump.sql' : 'sqlite3 mydb.db < dump.sql'}

`;
}
